
project_id = "qigkqfhtmhivxrfongzm"

[functions.analyze-and-generate-image]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.correct-content]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.publish-post]
verify_jwt = true
